export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const SET_MIN_RATING = "SET_MIN_RATING";

export const CREATE_NEW_USER_REVIEW = "CREATE_NEW_USER_REVIEW";

export const LOAD_ALL_RESTAURANTS = "LOAD_ALL_RESTAURANTS";
export const LOAD_RESTAURANTS_REVIEWS = "LOAD_RESTAURANTS_REVIEWS";
export const LOAD_RESTAURANT_DISHES = "LOAD_RESTAURANT_DISHES";

export const START = "_START";
export const SUCCESS = "_SUCCESS";
export const ERROR = "_ERROR";
